"""Add response models

Revision ID: 0ce0d4272569
Revises: b1d98191de78
Create Date: 2026-04-29 06:55:20.588804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce0d4272569'
down_revision: Union[str, None] = 'b1d98191de78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_condition', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('playbook_id', sa.String(length=36), nullable=True),
    sa.Column('playbook_name', sa.String(length=256), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('action_taken', sa.String(length=256), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('initiated_by', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_agents_group', table_name='agents')
    op.drop_index('idx_agents_status', table_name='agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_agents_status', 'agents', ['status'], unique=False)
    op.create_index('idx_agents_group', 'agents', ['group_name'], unique=False)
    op.drop_table('response_history')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
